name: Binary search - Typecheck (Mypy)

on:
        #  workflow_dispatch: {}
  push:
    branches:
      - 'main'
      #modyfing for push test
jobs:
  py-mypy-and-black:
    name: Binary search - Typecheck (Mypy)
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install mypy
    
    - run: mypy binary-search-typed.py
    
    - run: pip install black
      #check fails is black would reformat, succeeds if no changes
    - run: black --check binary-search-typed.py

